### ISSUE TITLE
[bug] Visual Studio 2022 Community - Build Error

### ISSUE THREAD

**Issue by JOHNYBGOOD1** [ssrlive/akelpad#2]
Hi.
I try to build on VS 2022 Community and i got errors.
I retarget the project from VS 2010 (since i really don't have 2010) to 22621 sdk VS 2022 and got error compiling.
![a](https://user-images.githubusercontent.com/121492869/209660296-6219646c-4aa0-4e3a-ad56-9da6dea42b00.jpg)
![b](https://user-images.githubusercontent.com/121492869/209660299-7d87242d-ed8e-4d74-a02d-1278f68b5c7d.jpg)

However if i link the coder.dll and macros.dll in options i can build but i got the error bellow (occasionally) !
![c akelpaderror](https://user-images.githubusercontent.com/121492869/209660396-e8d94d39-7e37-4239-b3d0-3f876f15494f.jpg)

Build in debug mode works flawless but in release mode x64 i got errors.
Any help really is welcome !
Thanks and **感謝** !

**Comment by ssrlive** [comment]
The weird bug can be fixed by close the Optimization switch.
