### ISSUE TITLE
Fail Fast Exception

### ISSUE THREAD

**Issue by nvdavsamd** [ssrlive/akelpad#3]
Hello,

I have a problem when building with VS 2022 Community.
I saw that was already reported, anyway pls do check it out!
![209660396-e8d94d39-7e37-4239-b3d0-3f876f15494f](https://user-images.githubusercontent.com/122004809/210721269-8906ed94-d15f-484e-a778-e9bbbca30fbf.jpg)

 i never had the above fast fail exception building from original https://sourceforge.net/p/akelpad/codesvn/HEAD/tree/trunk/akelpad_4/
in Microsoft Visual C++ Toolkit 2003 and Windows Server 2003 SP1 Platform SDK.

**Comment by nvdavsamd** [comment]
I work with big files over 200, 300 mb and more and i have the error above "Fail Fast Exception"

**i never had the error on** 
_https://sourceforge.net/p/akelpad/codesvn/HEAD/tree/trunk/akelpad_4/ build on in Microsoft Visual C++ Toolkit 2003 and Windows Server 2003 SP1 Platform SDK._

Anyway i stay with _https://sourceforge.net/p/akelpad/codesvn/HEAD/tree/trunk/akelpad_4/ build on in Microsoft Visual C++ Toolkit 2003 and Windows Server 2003 SP1 Platform SDK._ since is error free !

Thanks for your work anyway !

**Comment by ssrlive** [comment]
I'm not the author of this project. I just make the code can be compiled with VS 2010 and above.
so I can't anwser your questions.

**Comment by nvdavsamd** [comment]
![disable security check](https://user-images.githubusercontent.com/122004809/211216700-1a18db85-9659-47d2-9b78-23099787a7b3.jpg)
The fix is to "**Disable** Security Check" on ALL the file(s) !

So far i tested and i have no more "Fail Fast Exception" error when closing AkelPad, after working with hundreds of mb files, or different characters !

**Comment by nvdavsamd** [comment]
> I'm not the author of this project. I just make the code can be compiled with VS 2010 and above. so I can't anwser your questions.

You're doing a very good job mate, thank you so much.. AkelPad is the only Pad i ever use !
It is good to see that You made it work/compile on VS2022Community.

_Too bad that original akepad author has not updated the project for never versions other than vs 2003 or 2005._

I updated the original akelpad to be build from cmd fro newer vs2022community, but i prefer using your updated version.

Thanks again !
