### ISSUE TITLE
High DPi Resolutions Scale Fix

### ISSUE THREAD

**Issue by nvdavsamd** [ssrlive/akelpad#4]
Original with 125% scale
![NONdpiaware](https://user-images.githubusercontent.com/122004809/211218679-b2250bfa-eae4-4e91-b0cc-fe17912d1d36.jpg)

DPi Aware with 125% scale
![WITHdpiaware](https://user-images.githubusercontent.com/122004809/211218692-c6af9275-d8e4-483d-b0a7-9db57c7ce15a.jpg)

This is very important for high resolutions !
To fix this always enable in vs 2022 community
![high dpi aware](https://user-images.githubusercontent.com/122004809/211218790-bacf3953-5d84-4e70-9c7c-0ad0a52e80c6.jpg)

**Comment by nvdavsamd** [comment]
![dpiawarness](https://user-images.githubusercontent.com/122004809/211218975-c46af47b-86f3-487e-98a0-aac77542ad8b.jpg)

**Comment by ssrlive** [comment]
Better you provide a patch. I'm only using VS 2010 because my program has to be able to run on Windows XP and VS 2010 is the last compiler that supports XP.

**Comment by nvdavsamd** [comment]
XP ?!
You're joking right ?

I liked XP but in that era long ago. Now XP is just WASTE of ENERGY (Power Consumption)!
I runned XP sp2 from 2006 i think till 2017 February.
Then i was able to sell all computers XP based an desktop Athlon x2 64bit 4000+ (65 watt), Laptops 1 with T7500 (35 watt) and 2 an T5500 (45 watt), sold them all and bought in February 2017 an laptop with Apollo Lake N4200 + iGPU HD Graphics 505 = 10 watt  (hevc 8k 10bit hw decode, 4k vp9 10bit hw decode).
The N4200 at only 10 watt was faster than the 65watt+35watt+35watt above and i could add another 65watt !
So like i said Windows XP today is a serious waste of energy !

i jumped from XP straight to Windows 10 and skipped entirely Vista and 7 and 8, 8.1.

BTW use virtualbox + vs 2022 community and you can use vs 2015 tools from within vs 2022 community to build for XP !

About patching, well that is a problem, i removed all the code for 32bit, you will have to re-add again 32bit.
I don't use anymore 32bit, and with AkelPad i use files of many hundreds of mb, that make AkelPad go way, way over 2 gb.
I modified the cache to 512 mb in AkelPad, you will have to lower it for 32bit.

Also i modified the source code, and honestly i cut some plugins as you can notice in past issues posted by me.
I don't think patchind your code will be wise and it will take a loot of time.
I will post on git soon then you can see what you can chose and do for 32bit.

anyway good news till now i had 0 errors regarding fast fail.
also i modified the Redirect that Redirect Notepad.exe to AkelPad.exe and is now built in in and can be built from vs 2022 community latest 22621 !
![akelpadvs2022community22621](https://user-images.githubusercontent.com/122004809/211406369-20e7bca8-87d1-41bf-b95c-167b91f0f4f9.jpg)

**Comment by nvdavsamd** [comment]
i uploaded to github:
https://github.com/nvdavsamd/AkelPad

**Comment by ssrlive** [comment]
OK. good job. thanks a lot.
